[window]
padding.x = 25
padding.y = 20

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black   = '#101010'
red     = '#500505'
green   = '#053005'
yellow  = '#3A2000'
blue    = '#003060'
magenta = '#500A30'
cyan    = '#043040'
white   = '#A0A0A0'

[colors.bright]
black   = '#303030'
red     = '#A01010'
green   = '#057005'
yellow  = '#806000'
blue    = '#0060A0'
magenta = '#802060'
cyan    = '#0490A0'
white   = '#FFFFFF'
